package tdb.network;

public enum PacketType {
    USERNAME, DRAW_INPUT, ALERT, MESSAGE, LIST, DISCONNECT, USERNAME_ACK, 
    CLEAR_TO_DRAW, GAME_START, GAMESTATE_UPDATE, USER_DC, SERVER_DISCONNECT, 
    NEXT_ROUND, END_GAME, FOUND_WORD, TIME_UP, READY
}